source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Servers and Deployment -------------
gem 'whenever'      # Cronjobs
gem 'airbrake'      # Exception handling

# Databases --------------------------
gem 'pg'
gem "rails3_acts_as_paranoid" # Override default delete behavior

# Frontend ---------------------------

gem 'jquery-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

# Backend ----------------------------

# Inherited resources to simplify Controller logic
gem 'inherited_resources'
gem 'has_scope'

gem 'uuid'
gem 'dotenv-rails' #sets .env variables

# Tableless models
gem 'active_attr'

# Populate databases in development
group :development do
  gem 'faker'
  gem 'populator'
  gem 'capistrano' # Deploy with Capistrano
  gem 'capistrano_colors'
end
  
# APIs -------------------------------
gem 'snoo', git: 'git://github.com/yubrew/snoo.git', branch: 'development' # reddit api

# Rails/Ruby Console -----------------

# Syntax highlighting for IRB & rails console
gem 'wirble'  
gem 'awesome_print'

# Include Pry because it is used instead of IRB for rails c
gem 'pry-rails'
gem 'pry-doc'
gem 'pry-clipboard'

# Development ------------------------

group :development do
  gem 'rails_best_practices'
  gem 'commands' # do rails g and rake tasks in console
end

# Testing ----------------------------
group :test do
  gem "rspec-rails", "~> 2.0"
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
